sudo: false

language: scala

scala:
  - 2.12.8
  - 2.12.9
  - 2.13.0

jdk:
  - openjdk10
  - oraclejdk11

install: pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport && codecov

env:
  - CODECOV_TOKEN="ee86ed75-76a9-4ead-90a1-e7c97450257a"

after_success:
  - codecov
